# Generated by Django 5.1.6 on 2025-03-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_department_department_dep_name_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='acadamicyear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='acadamicyear',
            field=models.IntegerField(),
        ),
    ]
