# Generated by Django 5.1.6 on 2025-04-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_course_acadamicyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='Grade',
            field=models.CharField(default='NG', max_length=2),
        ),
    ]
