# Generated by Django 5.1.6 on 2025-04-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_assesment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='semister',
            field=models.IntegerField(default=1),
        ),
    ]
