# Generated by Django 5.1.6 on 2025-04-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_registration_semister'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semister',
            field=models.IntegerField(default=1),
        ),
    ]
