# Generated by Django 5.1.6 on 2025-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_course_semister'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='semister',
            field=models.IntegerField(default=1),
        ),
    ]
