# Generated by Django 5.1.6 on 2025-04-15 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_assesment_semister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_info', to='portal.studentprofile'),
        ),
    ]
