# Generated by Django 5.1.6 on 2025-04-15 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_assesment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='scgpa',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semister', models.IntegerField(default=1)),
                ('sgpa', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='portal.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'semister')},
            },
        ),
    ]
