# Generated by Django 5.1.6 on 2025-04-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_studentprofile_scgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
