# Generated by Django 5.1.6 on 2025-04-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_studentprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=400)),
                ('date', models.DateField(auto_now=True)),
                ('img', models.URLField(blank=True)),
            ],
        ),
    ]
