# Generated by Django 5.1.6 on 2025-10-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_announcement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semesterresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='acadamicyear',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='semesterresult',
            unique_together={('student', 'acadamicyear', 'semister')},
        ),
    ]
