# Generated by Django 5.1.6 on 2025-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_semesterresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='acadamicyear',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='registration',
            name='acadamicyear',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='acadamicyear',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='department',
            name='acadamicyear',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='acadamicyear',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='sgpa',
            field=models.FloatField(default=0.0),
        ),
    ]
